cleanup docker for readability

diff --git a/vscode/Dockerfile b/vscode/Dockerfile
--- a/vscode/Dockerfile
+++ b/vscode/Dockerfile
@@ -26,28 +26,28 @@ ARG HA_CLI_VERSION="4.37.0"
 # hadolint ignore=SC2181, DL3008
 RUN apt-get update && \
     apt-get install -y --no-install-recommends \
-        ack=3.6.0-1 \
-        libarchive-tools=3.6.2-1+deb12u2 \
-        build-essential=12.9 \
-        colordiff=1.0.20-1 \
-        git=1:2.39.5-0+deb12u2 \
-        iputils-ping=3:20221126-1+deb12u1 \
-        locales=2.36-9+deb12u7 \
-        mariadb-client=1:10.11.11-0+deb12u1 \
-        mosquitto-clients=2.0.11-1.2+deb12u1 \
-        net-tools=2.10-0.1 \
-        nmap=7.93+dfsg1-1 \
-        openssh-client=1:9.2p1-2+deb12u5 \
-        openssl=3.0.15-1~deb12u1 \
-        python3-dev=3.11.2-1+b1 \
-        python3=3.11.2-1+b1 \
-        unzip=6.0-28 \
-        uuid-runtime=2.38.1-5+deb12u1 \
-        wget \
-        zip=3.0-13 \
-        zsh=5.9-4+b5 \
-        less=590-2.1~deb12u2 \
-        htop=3.2.2-1 >=1.21.3-1+b2
+    ack=3.6.0-1 \
+    libarchive-tools=3.6.2-1+deb12u2 \
+    build-essential=12.9 \
+    colordiff=1.0.20-1 \
+    git=1:2.39.5-0+deb12u2 \
+    iputils-ping=3:20221126-1+deb12u1 \
+    locales=2.36-9+deb12u7 \
+    mariadb-client=1:10.11.11-0+deb12u1 \
+    mosquitto-clients=2.0.11-1.2+deb12u1 \
+    net-tools=2.10-0.1 \
+    nmap=7.93+dfsg1-1 \
+    openssh-client=1:9.2p1-2+deb12u5 \
+    openssl=3.0.15-1~deb12u1 \
+    python3-dev=3.11.2-1+b1 \
+    python3=3.11.2-1+b1 \
+    unzip=6.0-28 \
+    uuid-runtime=2.38.1-5+deb12u1 \
+    wget \
+    zip=3.0-13 \
+    zsh=5.9-4+b5 \
+    less=590-2.1~deb12u2 \
+    htop=3.2.2-1 >=1.21.3-1+b2
 
 RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
     locale-gen
@@ -56,28 +56,28 @@ RUN curl https://bootstrap.pypa.io/get-pip.py | python3 && \
     if [[ "${BUILD_ARCH}" = "aarch64" ]]; then ARCH="arm64"; fi && \
     if [[ "${BUILD_ARCH}" = "amd64" ]]; then ARCH="amd64"; fi
 
-   RUN  curl -fsSL https://code-server.dev/install.sh | sh
+RUN  curl -fsSL https://code-server.dev/install.sh | sh
 
-    # RUN uuid=$(uuidgen) &&
-    # while read -r ext; do
-    #     extention="${ext%%#*}" \
-    #         vendor="${extention%%.*}"
-    #     slug="${extention#*.}"
-    #     version="${ext##*#}"
+# RUN uuid=$(uuidgen) &&
+# while read -r ext; do
+#     extention="${ext%%#*}" \
+#         vendor="${extention%%.*}"
+#     slug="${extention#*.}"
+#     version="${ext##*#}"
 
-    #     echo "Installing vscode extension: ${slug} by ${vendor} @ ${version} "
+#     echo "Installing vscode extension: ${slug} by ${vendor} @ ${version} "
 
-    #     echo "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/${vendor}/vsextensions/${slug}/${version}/vspackage"
-    #     curl -JL --retry 5 -o "/tmp/${extention}-${version}.vsix" \
-    #         -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" \
-    #         -H "x-market-user-id: ${uuid}" \
-    #         "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/${vendor}/vsextensions/${slug}/${version}/vspackage"
-    #     mkdir -p "/usr/local/lib/code-server/lib/vscode/extensions/${extention}-${version}"
-    #     bsdtar --strip-components=1 -xf "/tmp/${extention}-${version}.vsix" \
-    #         -C "/usr/local/lib/code-server/lib/vscode/extensions/${extention}-${version}" extension
-    #     [ $? -ne 0 ] && exit 1
-    #     sleep 1
-    # done </root/vscode.extensions
+#     echo "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/${vendor}/vsextensions/${slug}/${version}/vspackage"
+#     curl -JL --retry 5 -o "/tmp/${extention}-${version}.vsix" \
+#         -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" \
+#         -H "x-market-user-id: ${uuid}" \
+#         "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/${vendor}/vsextensions/${slug}/${version}/vspackage"
+#     mkdir -p "/usr/local/lib/code-server/lib/vscode/extensions/${extention}-${version}"
+#     bsdtar --strip-components=1 -xf "/tmp/${extention}-${version}.vsix" \
+#         -C "/usr/local/lib/code-server/lib/vscode/extensions/${extention}-${version}" extension
+#     [ $? -ne 0 ] && exit 1
+#     sleep 1
+# done </root/vscode.extensions
 
 RUN ls -la /usr/local/lib/code-server/lib/vscode/extensions/ && \
     curl -L -s -o /usr/bin/ha "https://github.com/home-assistant/cli/releases/download/${HA_CLI_VERSION}/ha_${BUILD_ARCH}" && \
@@ -86,21 +86,21 @@ RUN ls -la /usr/local/lib/code-server/lib/vscode/extensions/ && \
 RUN git clone --branch master --single-branch --depth 1 \
     "https://github.com/robbyrussell/oh-my-zsh.git" ~/.oh-my-zsh &&\
     git clone --branch master --single-branch --depth 1 \
-        "https://github.com/zsh-users/zsh-autosuggestions" \
-        ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions && \
+    "https://github.com/zsh-users/zsh-autosuggestions" \
+    ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions && \
     git clone --branch master --single-branch --depth 1 \
-        "https://github.com/zsh-users/zsh-syntax-highlighting.git" \
-        ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting && \
+    "https://github.com/zsh-users/zsh-syntax-highlighting.git" \
+    ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting && \
     sed -i -e "s#bin/bash#bin/zsh#" /etc/passwd 
 
 RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10
 
 RUN pip3 install --no-cache-dir -r /tmp/requirements.txt && \
     apt-get purge -y --auto-remove \
-        build-essential \
-        libarchive-tools \
-        python3-dev \
-        uuid-runtime
+    build-essential \
+    libarchive-tools \
+    python3-dev \
+    uuid-runtime
 
 RUN find /usr/local \
     \( -type d -a -name test -o -name tests -o -name '__pycache__' \) \
