cleanup docker for readability

diff --git a/vscode/Dockerfile b/vscode/Dockerfile
--- a/vscode/Dockerfile
+++ b/vscode/Dockerfile
@@ -56,34 +56,28 @@ RUN curl https://bootstrap.pypa.io/get-pip.py | python3 &&
     if [[ "${BUILD_ARCH}" = "aarch64" ]]; then ARCH="arm64"; fi &&
     if [[ "${BUILD_ARCH}" = "amd64" ]]; then ARCH="amd64"; fi
 
-RUN curl -J -L -o /tmp/code.tar.gz \
-    "https://github.com/coder/code-server/releases/download/${CODE_SERVER_VERSION}/code-server-${CODE_SERVER_VERSION#v}-linux-${ARCH}.tar.gz" &&
-    mkdir -p /usr/local/lib/code-server &&
-    tar zxvf \
-        /tmp/code.tar.gz \
-        --strip 1 -C /usr/local/lib/code-server &&
-    ln -s /usr/local/lib/code-server/bin/code-server /usr/local/bin/code-server &&
-    mkdir -p /root/.code-server/extensions &&
-    uuid=$(uuidgen) &&
-    while read -r ext; do
-        extention="${ext%%#*}" \
-            vendor="${extention%%.*}"
-        slug="${extention#*.}"
-        version="${ext##*#}"
+   RUN  curl -fsSL https://code-server.dev/install.sh | sh
 
-        echo "Installing vscode extension: ${slug} by ${vendor} @ ${version} "
+    # RUN uuid=$(uuidgen) &&
+    # while read -r ext; do
+    #     extention="${ext%%#*}" \
+    #         vendor="${extention%%.*}"
+    #     slug="${extention#*.}"
+    #     version="${ext##*#}"
 
-        echo "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/${vendor}/vsextensions/${slug}/${version}/vspackage"
-        curl -JL --retry 5 -o "/tmp/${extention}-${version}.vsix" \
-            -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" \
-            -H "x-market-user-id: ${uuid}" \
-            "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/${vendor}/vsextensions/${slug}/${version}/vspackage"
-        mkdir -p "/usr/local/lib/code-server/lib/vscode/extensions/${extention}-${version}"
-        bsdtar --strip-components=1 -xf "/tmp/${extention}-${version}.vsix" \
-            -C "/usr/local/lib/code-server/lib/vscode/extensions/${extention}-${version}" extension
-        [ $? -ne 0 ] && exit 1
-        sleep 1
-    done </root/vscode.extensions
+    #     echo "Installing vscode extension: ${slug} by ${vendor} @ ${version} "
+
+    #     echo "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/${vendor}/vsextensions/${slug}/${version}/vspackage"
+    #     curl -JL --retry 5 -o "/tmp/${extention}-${version}.vsix" \
+    #         -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" \
+    #         -H "x-market-user-id: ${uuid}" \
+    #         "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/${vendor}/vsextensions/${slug}/${version}/vspackage"
+    #     mkdir -p "/usr/local/lib/code-server/lib/vscode/extensions/${extention}-${version}"
+    #     bsdtar --strip-components=1 -xf "/tmp/${extention}-${version}.vsix" \
+    #         -C "/usr/local/lib/code-server/lib/vscode/extensions/${extention}-${version}" extension
+    #     [ $? -ne 0 ] && exit 1
+    #     sleep 1
+    # done </root/vscode.extensions
 
 RUN ls -la /usr/local/lib/code-server/lib/vscode/extensions/ &&
     curl -L -s -o /usr/bin/ha "https://github.com/home-assistant/cli/releases/download/${HA_CLI_VERSION}/ha_${BUILD_ARCH}" &&
